ProyectoAPI/Controllers/PublicacionCRUDController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using ProyectoAPI.Models;
using ProyectoAPI.Models.ViewModel;
using ProyectoAPI.Services;

namespace ProyectoAPI.Controllers
{
    public class PublicacionCRUDController : Controller
    {
        private todaviasirveDBEntities db = new todaviasirveDBEntities();
        PublicacionService service = new PublicacionService();

        public ActionResult GuardarPublicacionCompleta(Publicacion publi,string[] pasos) {

            int files = Request.Files.Count;
            bool imagenDePublicacion = true;
            for (int i = 0; i < files; i++)
            {
                var imagen = Request.Files[i];
                if (imagen.ContentLength != 0)
                {
                    if (imagenDePublicacion)
                    {
                        var fileName = Path.GetFileName(imagen.FileName);
                        var imagenlocal = Path.Combine(
                        Server.MapPath("~/Content/images"), fileName);
                        imagen.SaveAs(imagenlocal);
                        publi.imagenPortada = fileName;
                        imagenDePublicacion = false;
                        db.Publicacion.Add(publi);
                        db.SaveChanges();
                    }
                    else
                    {
                        var fileName = Path.GetFileName(imagen.FileName);
                        var imagenlocal = Path.Combine(
                        Server.MapPath("~/Content/images"), fileName);
                        imagen.SaveAs(imagenlocal);
                        Paso paso = new Paso();
                        paso.idPublicacion = publi.id;
                        paso.descripcion = pasos[i - 1];
                        paso.imagen = fileName;
                        db.Paso.Add(paso);
                        db.SaveChanges();
                    }
                }

            }


            return View();
        }

        public ActionResult PublicacionesUsuario() {
            int idUsuario = (int)HttpContext.Session["idUsuario"];
            var publicacionesUsuario = service.ObtenerPublicacionesUsuario(idUsuario);
            return View("Index",publicacionesUsuario);
        }

        // GET: PublicacionCRUD
        public ActionResult Index()
        {

            return View(db.Publicacion.ToList());
        }

        // GET: PublicacionCRUD/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publicacion publicacion = db.Publicacion.Find(id);
            List<Paso> listadoPasos = db.Paso.Where(val => val.idPublicacion == id).ToList();
            if (publicacion == null)
            {
                return HttpNotFound();
            }
            if (listadoPasos != null) {
                ViewBag.listadoPasos = listadoPasos;
            }
            return View(publicacion);
        }

        // GET: PublicacionCRUD/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PublicacionCRUD/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "id,titulo,subtitulo,descripcion,fechaSubida,imagenPortada")] Publicacion publicacion)
        //{
                         
        //    if (ModelState.IsValid)
        //    {
        //        if (Request.Files.Count > 0)
        //        {
        //            HttpPostedFileBase file = Request.Files[0];
        //            if (file.ContentLength > 0)
        //            {
        //                var fileName = Path.GetFileName(file.FileName);
        //                var imagenlocal = Path.Combine(
        //                    Server.MapPath("~/Content/images"), fileName);
        //                file.SaveAs(imagenlocal);
        //                publicacion.imagenPortada = fileName;
        //            }
        //        }
        //        db.Publicacion.Add(publicacion);
        //        db.SaveChanges();

        //        return RedirectToAction("Index");
        //    }

        //    return View(publicacion);
        //}
        [HttpPost]
        public ActionResult Create(Publicacion publi)
        {
            int files = Request.Files.Count;
            var idUsuario = (int)HttpContext.Session["idUsuario"];
            Feedback publicacionUsuario = new Feedback();
            bool imagenDePublicacion = true;
            for (int i = 0; i < files; i++)
            {
                var imagen = Request.Files[i];
                if (imagen.ContentLength != 0)
                {
                    if (imagenDePublicacion)
                    {
                        var fileName = Path.GetFileName(imagen.FileName);
                        var imagenlocal = Path.Combine(
                        Server.MapPath("~/Content/images"), fileName);
                        imagen.SaveAs(imagenlocal);
                        publi.imagenPortada = fileName;
                        imagenDePublicacion = false;
                        db.Publicacion.Add(publi);
                        db.SaveChanges();
                        publicacionUsuario.idPublicacion = publi.id;
                        publicacionUsuario.idUsuario = idUsuario;
                        publicacionUsuario.fecha = new DateTime().ToString();
                        db.Feedback.Add(publicacionUsuario);
                        db.SaveChanges();
                    }
                    //else
                    //{
                    //    var fileName = Path.GetFileName(imagen.FileName);
                    //    var imagenlocal = Path.Combine(
                    //    Server.MapPath("~/Content/images"), fileName);
                    //    imagen.SaveAs(imagenlocal);
                    //    Paso paso = new Paso();
                    //    paso.idPublicacion = publi.id;
                    //    paso.descripcion = pasos[i-1];
                    //    paso.imagen = fileName;
                    //    db.Paso.Add(paso);
                    //    db.SaveChanges();
                    //}
                }

            }
         
            //List<HttpPostedFileBase> lista = null;
            


            //var valor = archivos.Files;
            //foreach (HttpPostedFileBase imagen in lista)
            //    {

            //        var fileName = Path.GetFileName(imagen.FileName);
            //        var imagenlocal = Path.Combine(
            //            Server.MapPath("~/Content/images"), fileName);
            //        imagen.SaveAs(imagenlocal);
            //    }

            
            //List<int> listado = new List<int>();
            //listado.Add(archivos1.Count);
            ////listado.Add(valor.Count);
            //ViewBag.listadoReconocido = listado;
            return RedirectToAction("Index");

        }

        [HttpPost]
        public ActionResult ReconocerImagen() {

            //HttpPostedFileBase file = Request.Files[0];
            //string valor;
            //if (file.ContentLength > 0)
            //{
            //    var fileName = Path.GetFileName(file.FileName);
            //    var imagenlocal = Path.Combine(
            //        Server.MapPath("~/Content/images"), fileName);
            //    file.SaveAs(imagenlocal);

            //}

            //Llamada a Imagga
            // Resultados en español : language=es 
            // Limite de resultados : limit=3 -- limit (default: -1 - meaning all tags)	
            //
            //HttpWebRequest request =
            //WebRequest.Create("https://api.imagga.com/v2/tags?image_url=https://s3.amazonaws.com/imagga-demo-uploads/tagging-demo/f067ff3435241405bd8d7901e1e348c7.jpg&language=es&limit=5")
            //as HttpWebRequest;
            //request.Method = "GET";
            ////request.ContentType = "application/x-www-form-urlencoded";
            //request.Accept = "application/json; charset=utf-8";
            //request.Headers.Add("Authorization", "Basic YWNjXzBlNTgzY2YyOTllNmIxNDowODU3ZjFkOGI4OWRjYjMwYWZiYjhjNmMwMzRlYmQxNA==");
            //// Metodo modificado
            //JsonImagga resultadoImagen;
            //string resp;

            //HttpWebResponse response = request.GetResponse() as HttpWebResponse;
            //Console.WriteLine("tamaño del contenido : {0}", response.ContentLength);
            //Console.WriteLine("Content type is {0}", response.ContentType);
            //using (StreamReader reader = new StreamReader(response.GetResponseStream(), Encoding.UTF8))
            ////using (Stream reader = response.GetResponseStream())
            //{
            //    resp = reader.ReadToEnd();
            //    //Console.WriteLine("Response stream received.");
            //    //Console.WriteLine(resp);

            //    //JsonSerializer js = new JsonSerializer();
            //    //JsonImagga obj = (JsonImagga)js.Deserialize(resp,typeof(JsonImagga));
            //    //var resultadoImagen = JsonConvert.DeserializeObject<JsonImagga>(reader);
            //    resultadoImagen = JsonConvert.DeserializeObject<JsonImagga>(resp);
            //    //foreach (var val in resultadoImagen)
            //    //{
            //    //    foreach (var valo in val.tags)
            //    //    {

ProyectoAPI/Views/PublicacionCRUD/Create.cshtml
@model ProyectoAPI.Models.Publicacion

@{
    ViewBag.Title = "Create";
}
<div class="micontainer">
    <div class="card">
        <div class="card-content">


            <h2>Crear Publicacion</h2>


            @using (Html.BeginForm("Create", "PublicacionCRUD", FormMethod.Post, new
            {
                enctype = "multipart/form-data"
            }))
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.subtitulo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.subtitulo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.subtitulo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.imagenPortada, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.imagenPortada, new { type = "file" })
                    </div>
                </div>
                <br />

                            @*imagenes de para subir*@@*
                    <h4>Ingrese los pasos y la descripcion</h4>
                    <div class="form-group">
                        @Html.Label("Ingresar imagen", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBox("imagen", "Examinar Imagen", new { type = "file" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Ingrese Descripcion", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="text" name="pasos" />
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.Label("Ingrese otra imagen", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBox("imagen", "Examinar Imagen", new { type = "file" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Ingrese Descripcion", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="text" name="pasos" />
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Ingrese otra imagen", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBox("imagen", "Examinar Imagen", new { type = "file" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Ingrese Descripcion", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="text" name="pasos" />
                        </div>
                    </div>*@


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoAPI/Views/PublicacionCRUD/Delete.cshtml
@model ProyectoAPI.Models.Publicacion

@{
    ViewBag.Title = "Delete";
}
<div class="micontainer">
    <div class="card">
        <h2>Delete</h2>
        <div class="card-content">
        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Publicacion</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.titulo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.titulo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.subtitulo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.subtitulo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.descripcion)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.descripcion)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.fechaSubida)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fechaSubida)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.imagenPortada)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.imagenPortada)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
        </div>
    </div>
</div>

ProyectoAPI/Views/PublicacionCRUD/Edit.cshtml
@model ProyectoAPI.Models.Publicacion

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "PublicacionCRUD", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="micontainer">
        <div class="row login justify-content-center">

            <div class="col col-md-8">
                <div class="card center-align col-md-12">

                    <div class="card-action teal green white-text">
                        <h4>Editar Publicación</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)
                    </div>

                    <div class="formularios-diseno card-content col-md-12">

                        <div class="form-group">
                            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label formularios-varios" })
                            <div class="col-md-10 boton-centrado">
                                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.subtitulo, htmlAttributes: new { @class = "control-label formularios-varios" })
                            <div class="col-md-10 boton-centrado">
                                @Html.EditorFor(model => model.subtitulo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.subtitulo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label formularios-varios" })
                            <div class="col-md-10 boton-centrado">
                                @Html.TextAreaFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.fechaSubida, htmlAttributes: new { @class = "control-label formularios-varios" })
                            <div class="col-md-10 boton-centrado">
                                @Html.EditorFor(model => model.fechaSubida, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.fechaSubida, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.imagenPortada, htmlAttributes: new { @class = "control-label formularios-varios" })
                            <div class="col-md-10 boton-centrado">
                                <img src="~/Content/Images/@Model.imagenPortada" class="img-thumbnail" />
                                @Html.EditorFor(model => model.imagenPortada, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.imagenPortada, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*@{ int contador = 1;}

                        @foreach (var item in Model.Paso)
                        {
                            @Html.HiddenFor(model => item.idPublicacion)
                            <div class="border">
                                <h6>Paso @contador</h6>
                                <div class="form-group">
                                    @Html.LabelFor(model => item.imagen, htmlAttributes: new { @class = "control-label formularios-varios" })
                                    <div class="col-md-10 boton-centrado">
                                        <img src="~/Content/Images/@item.imagen" class="img-thumbnail" />
                                        @Html.EditorFor(model => item.imagen, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => item.imagen, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => item.descripcion, htmlAttributes: new { @class = "control-label formularios-varios" })
                                    <div class="col-md-10 boton-centrado">
                                        @Html.TextAreaFor(model => item.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => item.descripcion, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            contador += 1;
                        }*@




                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10 boton-centrado">
                                <input type="submit" value="Guardar cambios" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
                <div>
                    @Html.ActionLink("Volver a detalles", "Index", null, new { @class = "btn btn-secondary btn-lg active" })
                </div>
            </div>

        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoAPI/Views/PublicacionCRUD/Index.cshtml
@model IEnumerable<ProyectoAPI.Models.Publicacion>

@{
    ViewBag.Title = "Lista de Publicaciones";
}
<div class="micontainer">
    <div class="micard">
        <h2>Publicaciones</h2>

        <p>
            @Html.ActionLink("Crear Publicacion", "Create","PublicacionCRUD",null, new { @class = "btn btn-success" } )
        </p>
        <table class="table table-striped">
            <thead class="mitabla">
                <tr>
                    
                    <th>
                        @Html.Label("TITULO")
                    </th>
                    <th>
                        @Html.Label("SUBTITULO")
                    </th>
                    <th>
                        @Html.Label("DESCRIPCION")
                    </th>
                    <th colspan="2" class="tam-opciones">
                        @Html.Label("OPCIONES")
                    </th>
                </tr>
            </thead>
            <tbody class="mitabla">
                @foreach (var item in Model)
                {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.titulo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.subtitulo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.descripcion)
                    </td>
                    
                    <td colspan="2">
                        
                            <a href="Details/@item.id" class="btn btnm-details"><i class="material-icons">info</i></a>
                            <a href="Edit/@item.id" class="btn"><i class="material-icons">edit</i></a>
                            <a href="Delete/@item.id" class="btn btnm-deleter"><i class="material-icons">delete</i></a>
                        
                    </td>
                </tr>
                }
            </tbody>
        </table>
        <br />
    </div>
</div>

ProyectoAPI/Views/PublicacionCRUD/ReconocerImagen.cshtml
@{
    ViewBag.Title = "Reconocer Imagen";
}
@model ProyectoAPI.Models.Publicacion
@*@model ProyectoAPI.Models.ViewModel.TablaPaso*@

<div class="container">
    <div class="card">
        <div class="card-content">


            <h2>Reconocimiento de Imagenes</h2>
            @using (Html.BeginForm("PostReconocerImagen", "PublicacionCRUD", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.subtitulo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.subtitulo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.subtitulo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.fechaSubida, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.fechaSubida, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.fechaSubida, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.imagenPortada, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.imagenPortada, new { type = "file" })
                    </div>
                </div>

                //imagenes de para subir 
                    <div class="form-group">
                        @Html.Label("Ingresar imagen a reconocer", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBox("imagen","Examinar Imagen", new { type = "file" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Ingrese Descripcion", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="text" name="pasos" />
                        </div>
                    </div>

                                          
                    <div class="form-group">
                        @Html.Label("Ingrese otra imagen", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBox("imagen", "Examinar Imagen", new { type = "file" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Ingrese Descripcion", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="text" name="pasos" />
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Ingrese otra imagen", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBox("imagen", "Examinar Imagen", new { type = "file" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Ingrese Descripcion", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="text" name="pasos" />
                        </div>
                    </div>

                if (ViewBag.listadoReconocido != null)
                {
                    foreach (int item in (List<int>)ViewBag.listadoReconocido)
                    {
                        <div class="form-group">
                            @Html.Label(item.ToString(), htmlAttributes: new { @class = "control-label col-md-6" })
                        </div>
                    }
                }
                else
                {
                    <div class="form-group">
                        @Html.Label("Sin resultados", htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                }
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Reconocer Imagen" class="btn btn-default" />
                    </div>
                </div>
                <br />
                <br />

            }

        </div>
    </div>
</div>